[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.26"
optimizer = true
optimizer_runs = 200
gas_reports = ["*"]

[rpc_endpoints]
arbitrum = "${ARBITRUM_RPC_URL}"
arbitrum_sepolia = "${ARBITRUM_SEPOLIA_RPC_URL}"

[etherscan]
arbitrum = { key = "${ARBISCAN_API_KEY}" }

